module.exports = {
  components: {
    categories: [
      {
        name: 'General',
        include: [
          'src/components/Alert/Alert.jsx',
          'src/components/AlertTitle/AlertTitle.jsx',
          'src/components/AlertDescription/AlertDescription.jsx',
          'src/components/AlertDialog/AlertDialog.jsx',
          'src/components/AlertDialogAction/AlertDialogAction.jsx',
          'src/components/AlertDialogCancel/AlertDialogCancel.jsx',
          'src/components/AlertDialogContent/AlertDialogContent.jsx',
          'src/components/AlertDialogDescription/AlertDialogDescription.jsx',
          'src/components/AlertDialogFooter/AlertDialogFooter.jsx',
          'src/components/AlertDialogHeader/AlertDialogHeader.jsx',
          'src/components/AlertDialogTitle/AlertDialogTitle.jsx',
          'src/components/AlertDialogTrigger/AlertDialogTrigger.jsx',
          'src/components/AlertDialogPortal/AlertDialogPortal.jsx',
          'src/components/AspectRatio/AspectRatio.jsx',
          'src/components/Button/Button.tsx',
          'src/components/Badge/Badge.jsx',
          'src/components/Card/Card.jsx',
          'src/components/CardContent/CardContent.jsx',
          'src/components/CardDescription/CardDescription.jsx',
          'src/components/CardFooter/CardFooter.jsx',
          'src/components/CardHeader/CardHeader.jsx',
          'src/components/CardTitle/CardTitle.jsx',
          'src/components/Checkbox/Checkbox.jsx',
          'src/components/Image/Image.js',
          'src/components/Slider/Slider.jsx',
          'src/components/Label/Label.jsx',
          'src/components/Pagination/Pagination.jsx',
          'src/components/PaginationContent/PaginationContent.jsx',
          'src/components/PaginationItem/PaginationItem.jsx',
          'src/components/PaginationLink/PaginationLink.jsx',
          'src/components/PaginationNext/PaginationNext.jsx',
          'src/components/PaginationPrevious/PaginationPrevious.jsx',
          'src/components/PaginationEllipsis/PaginationEllipsis.jsx',
        ],
      },
      {
        name: 'HTML',
        include: [
          'src/components/HtmlComponents/HtmlHeading/HtmlHeading.jsx',
          'src/components/HtmlComponents/HtmlText/HtmlText.jsx',
          'src/components/HtmlComponents/HtmlDiv/HtmlDiv.jsx',
          'src/components/HtmlComponents/HtmlList/HtmlList.jsx',
          'src/components/HtmlComponents/HtmlListItem/HtmlListItem.jsx',
          'src/components/HtmlComponents/HtmlTable/HtmlTable.jsx',
          'src/components/HtmlComponents/HtmlTableHead/HtmlTableHead.jsx',
          'src/components/HtmlComponents/HtmlTableBody/HtmlTableBody.jsx',
          'src/components/HtmlComponents/HtmlTableHeading/HtmlTableHeading.jsx',
          'src/components/HtmlComponents/HtmlTableRow/HtmlTableRow.jsx',
          'src/components/HtmlComponents/HtmlTableCell/HtmlTableCell.jsx',
          'src/components/HtmlComponents/HtmlTag/HtmlTag.jsx',
        ],
      },
    ],
    wrapper: 'src/components/UXPinWrapper/UXPinWrapper.js',
    webpackConfig: 'uxpin.webpack.config.js',
  },
  settings: { useUXPinProps: true, useConvertingToUXPinClassic: true },
  name: 'ShadCN Design System',
};
